// <auto-generated />
using System;
using LC.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace LC.Persistence.Migrations
{
    [DbContext(typeof(DataBaseContext))]
    partial class DataBaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("LC.Domain.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnName("AUTHOR");

                    b.Property<DateTime>("CreatdAt")
                        .HasColumnName("CREATED_AT");

                    b.Property<string>("DescriptionLong")
                        .HasColumnName("DESCRIPTION_LONG");

                    b.Property<string>("DescriptionShort")
                        .HasColumnName("DESCRIPTION_SHORT");

                    b.Property<string>("Language")
                        .HasColumnName("LANGUAGE");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnName("NAME");

                    b.Property<string>("Photo")
                        .IsRequired()
                        .HasColumnName("PHOTO");

                    b.Property<decimal>("Price")
                        .HasColumnName("PRICE")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Publishing")
                        .IsRequired()
                        .HasColumnName("PUBLISHING");

                    b.Property<int>("QuantityPages")
                        .HasColumnName("QUANTITY_PAGES");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnName("SLUG");

                    b.Property<string>("Weight")
                        .HasColumnName("WEIGHT");

                    b.Property<int>("Year")
                        .HasColumnName("YEAR");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("TB_BOOKS");
                });
#pragma warning restore 612, 618
        }
    }
}
