// <auto-generated />
using System;
using LivrariaJc.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LivrariaJc.Data.Migrations
{
    [DbContext(typeof(LivrariaJcContext))]
    partial class LivrariaJcContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LivrariaJc.Domain.Entidades.LivrosEntidade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Autor")
                        .HasMaxLength(140)
                        .HasColumnType("nvarchar(140)");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataLancamento")
                        .HasColumnType("datetime2");

                    b.Property<string>("Titulo")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<decimal>("Valor")
                        .HasPrecision(10, 4)
                        .HasColumnType("decimal(10,4)");

                    b.HasKey("Id");

                    b.ToTable("Livros", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Autor = "William Shakespeare",
                            DataCriacao = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataLancamento = new DateTime(1875, 7, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Titulo = "Romeu e Julieta",
                            Valor = 160.00m
                        },
                        new
                        {
                            Id = 2,
                            Autor = "Pero Vaz de Caminha",
                            DataCriacao = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataLancamento = new DateTime(1842, 10, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Titulo = "Carta de Pero Vaz de Caminha",
                            Valor = 100.00m
                        },
                        new
                        {
                            Id = 3,
                            Autor = "Afonso Henriques de Lima Barreto",
                            DataCriacao = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataLancamento = new DateTime(1985, 1, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Titulo = "Triste Fim de Policarpo Quaresma: análise, contexto histórico e mais",
                            Valor = 50.00m
                        },
                        new
                        {
                            Id = 4,
                            Autor = "Gil Vicente",
                            DataCriacao = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataLancamento = new DateTime(2001, 4, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Titulo = "Auto da Barca do Inferno",
                            Valor = 40.00m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
