export enum ApiController {
    Adicionais = 'adicionais',
    AdicionalSalarial = 'adicionais/adicionalsalarial',
    Agendamento = 'agendamento',
    Atividade = 'atividade',
    Biometria = 'biometria',
    CalendarioPonto = 'calendarioponto',
    Cargo = 'cargo',
    Competencia = 'competencia',
    Departamento = 'departamento',
    Empresa = 'empresa',
    Funcao = 'funcao',
    Login = 'login',
    Lotacao = 'lotacao',
    NivelAcesso = 'nivelacesso',
    Orgao = 'orgao',
    PessoaSituacao = 'pessoasituacao',
    Pessoa = 'pessoa',
    Ponto = 'ponto',
    Rastreamento = 'rastreamento',
    TipoProgramacao = 'tipoprogramacao',
    Usuarios = 'usuarios'
}
