CREATE DATABASE LivrariaDB
GO

USE LivrariaDB
GO

CREATE TABLE LIVRO 
(
	LIVROID UNIQUEIDENTIFIER PRIMARY KEY NOT NULL,
	ISBN NVARCHAR(13) NOT NULL,
	TITULO NVARCHAR(80) NOT NULL,
	GENERO NVARCHAR(80) NOT NULL,
	QTD_PAGINAS INT NOT NULL,
	NOME_AUTOR NVARCHAR(80) NOT NULL
)
GO